services:
  rainscale:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/rainscale:/rainscale
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./backend/dotenv_files/.env
    # depends_on:
    #   - psql
    networks:
      - network
  
  # psql:
  #   container_name: psql
  #   image: postgres:13
  #   volumes:
  #     - ./data/postgres/data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./backend/dotenv_files/.env
  #   networks:
  #     - network

networks:
  network:
    driver: bridge